name: Create Artifact

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: order-service
          path: .
